Callback for PIP mode
gunschu/jitsi_meet pull request #82
Opened 2020-07-30 12:18 UTC by Snapworks

Listener added to capture Jitsi's entry and exist from PIP mode

Sample usage in dart code..

Add Listener
```

JitsiMeet.addListener(JitsiMeetingListener(
        onConferenceWillJoin: _onConferenceWillJoin,
        onConferenceJoined: _onConferenceJoined,
        onConferenceTerminated: _onConferenceTerminated,
        onPictureInPictureWillEnter: _onPictureInPictureWillEnter,
        onPictureInPictureTerminated: _onPictureInPictureTerminated,
        onError: _onError));
```

Then
```

_onPictureInPictureWillEnter({message}) {
    print("_onPictureInPictureWillEnter");
  }

  _onPictureInPictureTerminated({message}) {
    print("_onPictureInPictureTerminated");
  }
```

2020-09-06 19:11 UTC, tuantvu requested changes

2020-09-06 19:11 UTC, tuantvu commented on android/src/main/kotlin/com/gunschu/jitsi_meet/JitsiMeetPluginActivity.kt
> +
Let's remove all these extra blank lines.

2020-09-06 19:11 UTC, tuantvu commented on ios/Classes/JitsiViewController.swift
> +    func exitPictureInPicture() {
Could  this function be moved to the same extension class as the enterPictureInPicture function?

2020-09-06 19:11 UTC, tuantvu commented on ios/Classes/JitsiViewController.swift
> +
Please remove all extra blank lines

2020-09-06 19:11 UTC, tuantvu commented on ios/Classes/JitsiViewController.swift
> +    func exitPictureInPicture() {
Is this function overriding some function in PiPViewCoordinatorDelegate?

2020-09-06 19:11 UTC, tuantvu commented on lib/jitsi_meeting_listener.dart
> +        this.onPictureInPictureWillEnter,
remove extra indent.

2020-09-12 09:58 UTC, Snapworks commented
I will refactor the code and do a PR again.. not sure whats messing up my formatting when I submit.

2020-11-25 12:51 UTC, Snapworks commented
Code updated and merged through another pull request.

2020-11-25 12:51 UTC, closed without merging